server:
  port: 8082
spring:  
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://db-equipos:3306/db-equipos
    username: root
    password: 1234