server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    
      routes:
        - id: ms-profesores
          uri: http://ms-profesores:8081
          predicates:
            - Path=/api/profesores/**        
        - id: ms-equipos
          uri: http://ms-equipos:8082
          predicates:
            - Path=/api/equipos/**, /api/catalogo/**
        - id: ms-prestamos
          uri: http://ms-prestamos:8083
          predicates:
            - Path=/api/prestamos/**, /api/devoluciones/**, /api/reportes/prestamos/**