server:
  port: 8081
spring:  
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://db-profesores:3306/db-profesores
    username: root
    password: 1234
