server:
  port: 8083
spring:  
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://db-prestamos:3306/db-prestamos
    username: root
    password: 1234